server:
  port: 8011
  servlet:
    context-path: /activiti
spring:
  activiti:
    database-schema-update: true #自动更新数据库结构
    history-level: full
    check-process-definitions: true    #自动检查、部署流程定义文件
    process-definition-location-prefix: classpath:/processes/  #流程定义文件存放目录
  datasource:
    name: connectJudgementSystem
    url: jdbc:mysql://localhost:3306/judge?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 500
      minimum-idle: 1
      idle-timeout: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.judgesystem.entity
