server:
  port: 8013
spring:
  datasource:
    name: connectJudgementSystem
    url: jdbc:mysql://localhost:3306/judge?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.judgesystem.entity